<?php

namespace AppBundle\Repository;

/**
 * Cli_clientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cli_clientRepository extends \Doctrine\ORM\EntityRepository
{

}
