<?php

namespace AppBundle\Repository;

/**
 * Com_commentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Com_commentaireRepository extends \Doctrine\ORM\EntityRepository
{
}
