<?php

namespace AppBundle\Repository;

/**
 * Pho_photoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Pho_photoRepository extends \Doctrine\ORM\EntityRepository
{
}
