<?php

namespace AppBundle\Repository;

/**
 * TRA_travailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TRA_travailRepository extends \Doctrine\ORM\EntityRepository
{
}
