<?php

namespace AppBundle\Repository;

/**
 * Uti_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Uti_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
